{% set name = "grep-ast" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/grep_ast-{{ version }}.tar.gz
  sha256: 42b8887d57301dc55634368f8d549e9c49c913dafb4d19c9b54c3ddb604fccf4

build:
  entry_points:
    - grep-ast=grep_ast.main:main
    - gast=grep_ast.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - tree_sitter_languages >=1.8.0
    - pathspec

test:
  imports:
    - grep_ast
  commands:
    - pip check
    - grep-ast --help
    - gast --help
  requires:
    - pip

about:
  home: https://github.com/paul-gauthier/grep-ast
  summary: A tool to grep through the AST of a source file
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
